// <auto-generated />
namespace Solution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class contrat1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contrat1));
        
        string IMigrationMetadata.Id
        {
            get { return "202006092330416_contrat1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
